package pl.proenix.android.us2pum.lab2countriesisocode;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.Toast;

public class MainActivity extends Activity {

    private String[] countryNames;

    @Override
    protected void onCreate(Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        ListView listView = findViewById(R.id.list);
        countryNames = new String[]{
                "Afganistan",
                "Albania",
                "Algieria",
                "Andora",
                "Angola",
                "Anguilla",
                "Antarktyka",
                "Antigua i Barbuda",
                "Arabia Saudyjska",
                "Argentyna",
                "Armenia",
                "Aruba",
                "Australia",
                "Austria",
                "Azerbejdżan",
                "Bahamy",
                "Bahrajn",
                "Bangladesz",
                "Barbados",
                "Belgia",
                "Belize",
                "Benin",
                "Bermudy",
                "Bhutan",
                "Białoruś",
                "Boliwia",
                "Bonaire, Sint Eustatius i Saba",
                "Bośnia i Hercegowina",
                "Botswana",
                "Brazylia",
                "Brunei",
                "Brytyjskie Terytorium Oceanu Indyjskiego",
                "Brytyjskie Wyspy Dziewicze",
                "Bułgaria",
                "Burkina Faso",
                "Burundi",
                "Chile",
                "Chiny",
                "Chorwacja",
                "Curaçao",
                "Cypr",
                "Czad",
                "Czarnogóra",
                "Czechy",
                "Dalekie Wyspy Mniejsze Stanów Zjednoczonych",
                "Dania",
                "Demokratyczna Republika Konga",
                "Dominika",
                "Dominikana",
                "Dżibuti",
                "Egipt",
                "Ekwador",
                "Erytrea",
                "Estonia",
                "Eswatini",
                "Etiopia",
                "Falklandy",
                "Fidżi",
                "Filipiny",
                "Finlandia",
                "Francja",
                "Francuskie Terytoria Południowe i Antarktyczne",
                "Gabon",
                "Gambia",
                "Georgia Południowa i Sandwich Południowy",
                "Ghana",
                "Gibraltar",
                "Grecja",
                "Grenada",
                "Grenlandia",
                "Gruzja",
                "Guam",
                "Guernsey",
                "Gujana",
                "Gujana Francuska",
                "Gwadelupa",
                "Gwatemala",
                "Gwinea",
                "Gwinea Bissau",
                "Gwinea Równikowa",
                "Haiti",
                "Hiszpania",
                "Holandia",
                "Honduras",
                "Hongkong",
                "Indie",
                "Indonezja",
                "Irak",
                "Iran",
                "Irlandia",
                "Islandia",
                "Izrael",
                "Jamajka",
                "Japonia",
                "Jemen",
                "Jersey",
                "Jordania",
                "Kajmany",
                "Kambodża",
                "Kamerun",
                "Kanada",
                "Katar",
                "Kazachstan",
                "Kenia",
                "Kirgistan",
                "Kiribati",
                "Kolumbia",
                "Komory",
                "Kongo",
                "Korea Południowa",
                "Korea Północna",
                "Kostaryka",
                "Kuba",
                "Kuwejt",
                "Laos",
                "Lesotho",
                "Liban",
                "Liberia",
                "Libia",
                "Liechtenstein",
                "Litwa",
                "Luksemburg",
                "Łotwa",
                "Macedonia Północna",
                "Madagaskar",
                "Majotta",
                "Makau",
                "Malawi",
                "Malediwy",
                "Malezja",
                "Mali",
                "Malta",
                "Mariany Północne",
                "Maroko",
                "Martynika",
                "Mauretania",
                "Mauritius",
                "Meksyk",
                "Mikronezja",
                "Mjanma",
                "Mołdawia",
                "Monako",
                "Mongolia",
                "Montserrat",
                "Mozambik",
                "Namibia",
                "Nauru",
                "Nepal",
                "Niemcy",
                "Niger",
                "Nigeria",
                "Nikaragua",
                "Niue",
                "Norfolk",
                "Norwegia",
                "Nowa Kaledonia",
                "Nowa Zelandia",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestyna",
                "Panama",
                "Papua-Nowa Gwinea",
                "Paragwaj",
                "Peru",
                "Pitcairn",
                "Polinezja Francuska",
                "Polska",
                "Południowa Afryka",
                "Portoryko",
                "Portugalia",
                "Republika Środkowoafrykańska",
                "Republika Zielonego Przylądka",
                "Reunion",
                "Rosja",
                "Rumunia",
                "Rwanda",
                "Sahara Zachodnia",
                "Saint Kitts i Nevis",
                "Saint Lucia",
                "Saint Vincent i Grenadyny",
                "Saint-Barthélemy",
                "Saint-Martin",
                "Saint-Pierre i Miquelon",
                "Salwador",
                "Samoa",
                "Samoa Amerykańskie",
                "San Marino",
                "Senegal",
                "Serbia",
                "Seszele",
                "Sierra Leone",
                "Singapur",
                "Sint Maarten",
                "Słowacja",
                "Słowenia",
                "Somalia",
                "Sri Lanka",
                "Stany Zjednoczone",
                "Sudan",
                "Sudan Południowy",
                "Surinam",
                "Svalbard i Jan Mayen",
                "Syria",
                "Szwajcaria",
                "Szwecja",
                "Tadżykistan",
                "Tajlandia",
                "Tajwan",
                "Tanzania",
                "Timor Wschodni",
                "Togo",
                "Tokelau",
                "Tonga",
                "Trynidad i Tobago",
                "Tunezja",
                "Turcja",
                "Turkmenistan",
                "Turks i Caicos",
                "Tuvalu",
                "Uganda",
                "Ukraina",
                "Urugwaj",
                "Uzbekistan",
                "Vanuatu",
                "Wallis i Futuna",
                "Watykan",
                "Wenezuela",
                "Węgry",
                "Wielka Brytania",
                "Wietnam",
                "Włochy",
                "Wybrzeże Kości Słoniowej",
                "Wyspa Bouveta",
                "Wyspa Bożego Narodzenia",
                "Wyspa Man",
                "Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha",
                "Wyspy Alandzkie",
                "Wyspy Cooka",
                "Wyspy Dziewicze Stanów Zjednoczonych",
                "Wyspy Heard i McDonalda",
                "Wyspy Kokosowe",
                "Wyspy Marshalla",
                "Wyspy Owcze",
                "Wyspy Salomona",
                "Wyspy Świętego Tomasza i Książęca",
                "Zambia",
                "Zimbabwe",
                "Zjednoczone Emiraty Arabskie",
        };
        String[] countryISOCodes = new String[]{
                "AF",
                "AL",
                "DZ",
                "AD",
                "AO",
                "AI",
                "AQ",
                "AG",
                "SA",
                "AR",
                "AM",
                "AW",
                "AU",
                "AT",
                "AZ",
                "BS",
                "BH",
                "BD",
                "BB",
                "BE",
                "BZ",
                "BJ",
                "BM",
                "BT",
                "BY",
                "BO",
                "BQ",
                "BA",
                "BW",
                "BR",
                "BN",
                "IO",
                "VG",
                "BG",
                "BF",
                "BI",
                "CL",
                "CN",
                "HR",
                "CW",
                "CY",
                "TD",
                "ME",
                "CZ",
                "UM",
                "DK",
                "CD",
                "DM",
                "DO",
                "DJ",
                "EG",
                "EC",
                "ER",
                "EE",
                "SZ",
                "ET",
                "FK",
                "FJ",
                "PH",
                "FI",
                "FR",
                "TF",
                "GA",
                "GM",
                "GS",
                "GH",
                "GI",
                "GR",
                "GD",
                "GL",
                "GE",
                "GU",
                "GG",
                "GY",
                "GF",
                "GP",
                "GT",
                "GN",
                "GW",
                "GQ",
                "HT",
                "ES",
                "NL",
                "HN",
                "HK",
                "IN",
                "ID",
                "IQ",
                "IR",
                "IE",
                "IS",
                "IL",
                "JM",
                "JP",
                "YE",
                "JE",
                "JO",
                "KY",
                "KH",
                "CM",
                "CA",
                "QA",
                "KZ",
                "KE",
                "KG",
                "KI",
                "CO",
                "KM",
                "CG",
                "KR",
                "KP",
                "CR",
                "CU",
                "KW",
                "LA",
                "LS",
                "LB",
                "LR",
                "LY",
                "LI",
                "LT",
                "LU",
                "LV",
                "MK",
                "MG",
                "YT",
                "MO",
                "MW",
                "MV",
                "MY",
                "ML",
                "MT",
                "MP",
                "MA",
                "MQ",
                "MR",
                "MU",
                "MX",
                "FM",
                "MM",
                "MD",
                "MC",
                "MN",
                "MS",
                "MZ",
                "NA",
                "NR",
                "NP",
                "DE",
                "NE",
                "NG",
                "NI",
                "NU",
                "NF",
                "NO",
                "NC",
                "NZ",
                "OM",
                "PK",
                "PW",
                "PS",
                "PA",
                "PG",
                "PY",
                "PE",
                "PN",
                "PF",
                "PL",
                "ZA",
                "PR",
                "PT",
                "CF",
                "CV",
                "RE",
                "RU",
                "RO",
                "RW",
                "EH",
                "KN",
                "LC",
                "VC",
                "BL",
                "MF",
                "PM",
                "SV",
                "WS",
                "AS",
                "SM",
                "SN",
                "RS",
                "SC",
                "SL",
                "SG",
                "SX",
                "SK",
                "SI",
                "SO",
                "LK",
                "US",
                "SD",
                "SS",
                "SR",
                "SJ",
                "SY",
                "CH",
                "SE",
                "TJ",
                "TH",
                "TW",
                "TZ",
                "TL",
                "TG",
                "TK",
                "TO",
                "TT",
                "TN",
                "TR",
                "TM",
                "TC",
                "TV",
                "UG",
                "UA",
                "UY",
                "UZ",
                "VU",
                "WF",
                "VA",
                "VE",
                "HU",
                "GB",
                "VN",
                "IT",
                "CI",
                "BV",
                "CX",
                "IM",
                "SH",
                "AX",
                "CK",
                "VI",
                "HM",
                "CC",
                "MH",
                "FO",
                "SB",
                "ST",
                "ZM",
                "ZW",
                "AE",
        };

        ArrayAdapter<String> adapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, countryISOCodes);
        listView.setAdapter(adapter);
        listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Toast.makeText(getApplicationContext(), countryNames[position], Toast.LENGTH_LONG).show();
            }
        });
    }
}
